### PR TITLE
support null safety

### PR DESCRIPTION
**Pull request by leventkantaroglu**

### CODE REVIEW

**Comment by leventkantaroglu** [comment]
Review is required

**Comment by aloklearning** [comment]
Hello @leventkantaroglu, since I do not have enough time to test the code. Are you confident that this works functionally fine? If yes, then I will merge the code, and push it to the **Flutter Pub Dev** website. Will be waiting for your confirmation. 

Regards
Alok (Author of Flutter Bounce Package)

**Comment by ghost** [comment]
Yes, just null-safety support is added. Functionally is still stable. I tested on my locale 👍

**Comment by aloklearning** [comment]
Awesome @leventkantaroglu, I was also expecting the same, but unsure, since I could not test the code. Thank you very much for your contribution. Many of our community members will get benefited from this surely. 

Best Regards
Alok

**Pull request merged**
